parameters:
  - name: ProjectName
    displayName: Project Name
    type: string
    default: Project1
    values:
      - Project1
resources:
 repositories:
   - repository: templates
     name: kumar-grsi/shared-cicd-repo
     type: github
     ref: main
     endpoint: github-login-kumar
      
stages:
- template: shared-pipelines.yml@templates
  parameters: 
   ProjectName: ${{ parameters.ProjectName}}